const players = [
    {
        //NAME
        firstName: 'Kirby',
        //NAME
        alt: 'Kirby',
        //from
        lastName: 'Planet Popstar',
        //wepon
        position: 'Mouth',
        //games in
        age: 50,
        //charcter immage
        photo: 'imgs/char/kirby.webp',
        //charcter icon
        pic: 'imgs/char/icons/KSA_Normal_icon.png',
        //add new image for modal
        photoALT: 'imgs/char/more/kirbyOG.png',
        //add the fact
        fact: 'By sucking in emmies, he can copy almost any ability!',
    }, {
        firstName: 'King Dedede',
        alt: 'King',
        lastName: 'Planet Popstar',
        position: 'Hammer',
        age: 49,
        photo: 'imgs/char/dedede.png',
        pic: 'imgs/char/icons/KSA_King_Dedede_icon.png',
        photoALT: 'imgs/char/more/king.png',
        fact: 'He has his own drumming spin off game!',
    }, {
        firstName: 'Meta Knight',
        alt: 'Meta',
        lastName: 'Planet Popstar',
        position: 'Sword',
        age: 12,
        photo: 'imgs/char/MK.webp',
        pic: 'imgs/char/icons/KSA_Meta_Knight_icon.png',
        photoALT: 'imgs/char/more/metta.png',
        fact: 'Meta Knight handles with a permanent mix of the Sword and Wing abilities',
    }, {
        firstName: 'Bandana Waddle Dee',
        alt: 'Bandana',
        lastName: 'Planet Popstar',
        position: 'Spear',
        age: 10,
        photo: 'imgs/char/bandana.png',
        pic: 'imgs/char/icons/KSA_Bandana_Waddle_Dee_icon.png',
        photoALT: 'imgs/char/more/ban.png',
        fact: 'Bandana Waddle Dee debuted in Kirby Super Star as the first opponent in Megaton Punch. ',
    }, {
        firstName: 'Gooey',
        alt: 'Gooey',
        lastName: 'Planet Popstar',
        position: 'Tongue',
        age: 5,
        photo: 'imgs/char/gooey.webp',
        pic: 'imgs/char/icons/KSA_Gooey_icon.png',
        photoALT: 'imgs/char/more/goo.png',
        fact: 'Gooey can grab enemies with his long tongue, spit them out as a Star Bullet or swallow them to potentially gain a Copy Ability',
    }, {
        firstName: 'Marx',
        alt: 'Marx',
        lastName: 'Planet Popstar',
        position: 'Balls',
        age: 5,
        photo: 'imgs/char/marax.png',
        pic: 'imgs/char/icons/KSA_Marx_icon.png',
        photoALT: 'imgs/char/more/mar.png',
        fact: 'Marx is a character in the Kirby series, debuting as the main antagonist and final boss of the sub-game Milky Way Wishes in Kirby Super Star and its remake, Kirby Super Star Ultra, as well as the final boss of the two games in general.',
    }, {
        firstName: 'Dark Meta Knight',
        alt: 'Dark',
        lastName: 'Mirror World',
        position: 'Sword',
        age: 4,
        photo: 'imgs/char/dark.png',
        pic: 'imgs/char/icons/KSA_Dark_Meta_Knight_icon.png',
        photoALT: 'imgs/char/more/dark.png',
        fact: 'Dark Meta Knight is a mirror image of Meta Knight from the Mirror World.',
    }, {
        firstName: 'Adeleine',
        alt: 'Adeleine',
        lastName: 'Planet Popstar',
        position: 'Paintbrush',
        age: 3,
        photo: 'imgs/char/adeleine.png',
        pic: 'imgs/char/icons/KSA_Adeleine_&_Ribbon_icon.png',
        photoALT: 'imgs/char/more/add.png',
        fact: 'Adeleine is an artist who makes her home on Planet Popstar',
    }, {
        firstName: 'Ribbon',
        alt: 'Ribbon',
        lastName: 'Ripple Star',
        position: 'Crystal',
        age: 3,
        photo: 'imgs/char/Ribbon.webp',
        pic: 'imgs/char/icons/KSA_Adeleine_&_Ribbon_icon.png',
        photoALT: 'imgs/char/more/rib.png',
        fact: 'Ribbon is a small fairy from Ripple Star who made her debut in Kirby 64: The Crystal Shards',
    }, {
        firstName: 'Taranza',
        alt: 'Taranza',
        lastName: 'Floralia',
        position: 'Spider Magic',
        age: 2,
        photo: 'imgs/char/taranza.png',
        pic: 'imgs/char/icons/KSA_Taranza_icon.png',
        photoALT: 'imgs/char/more/tan.png',
        fact: 'Taranza is a young, clumsy wizard with arachnid-like characteristics who serves as a prominent character in a few games in the Kirby series',
    }, {
        firstName: 'Susie',
        alt: 'Susie',
        lastName: 'Haltmann Works Company',
        position: 'Robotics',
        age: 2,
        photo: 'imgs/char/susie.png',
        pic: 'imgs/char/icons/KSA_Susie_icon.png',
        photoALT: 'imgs/char/more/bot.png',
        fact: 'In Susie`s debut appearance, she was a villain and antagonist to Kirby, fighting him personally as a boss and later sending other creations of Haltmann Works after him, while also being the primary source of information about the company',
    }, {
        firstName: 'Magolor',
        alt: 'Magolor',
        lastName: 'Hancaldra',
        position: 'Magic',
        age: 4,
        photo: 'imgs/char/magalor.png',
        pic: 'imgs/char/icons/KSA_Magolor_icon.png',
        photoALT: 'imgs/char/more/mag.png',
        fact: 'Magolor is a cat-like alien magician who first appeared in Kirby`s Return to Dream Land as the main antagonist',
    }, {
        firstName: 'Rick',
        alt: 'Rick',
        lastName: 'Planet Popstar',
        position: 'Himself',
        age: 4,
        photo: 'imgs/char/rick.png',
        pic: 'imgs/char/icons/KSA_Rick_&_Kine_&_Coo_icon.png',
        photoALT: 'imgs/char/more/ric.png',
        fact: 'Rick is a hamster-like character and an Animal Friend of Kirby',
    }, {
        firstName: 'Kine',
        alt: 'Kine',
        lastName: 'Planet Popstar',
        position: 'Bubbles',
        age: 4,
        photo: 'imgs/char/kine.png',
        pic: 'imgs/char/icons/KSA_Rick_&_Kine_&_Coo_icon.png',
        photoALT: 'imgs/char/more/kine.png',
        fact: 'A blue fish who can swim against strong currents and allow Kirby to use his inhaling attack underwater',
    }, {
        firstName: 'Coo',
        alt: 'Coo',
        lastName: 'Planet Popstar',
        position: 'Wings',
        age: 4,
        photo: 'imgs/char/coo.webp',
        pic: 'imgs/char/icons/KSA_Rick_&_Kine_&_Coo_icon.png',
        photoALT: 'imgs/char/more/coo.png',
        fact: 'Coo is a prominent Animal Friend in the Kirby series, known for his flying ability and calm demeanor',
    }, {
        firstName: 'Flamberge',
        alt: 'Flamberge',
        lastName: 'Planet Popstar',
        position: 'Fire Magic',
        age: 1,
        photo: 'imgs/char/Flamberge.webp',
        pic: 'imgs/char/icons/KSA_The_Three_Mage-Sisters_icon.png',
        photoALT: 'imgs/char/more/flame.webp',
        fact: 'Flamberge is a fiery boss character introduced in Kirby Star Allies, known as the Blazing General of The Three Mage-Sister',
    }, {
        firstName: 'Francisca',
        alt: 'Francisca',
        lastName: 'Planet Popstar',
        position: 'Ice Magic',
        age: 1,
        photo: 'imgs/char/Francisca.png',
        pic: 'imgs/char/icons/KSA_The_Three_Mage-Sisters_icon.png',
        photoALT: 'imgs/char/more/fra.png',
        fact: 'Francisca is a frozen boss character introduced in Kirby Star Allies, known as the Frozen General of The Three Mage-Sister',
    }, {
        firstName: 'Zan Partizanne',
        alt: 'Zan',
        lastName: 'Planet Popstar',
        position: 'Thunder Magic',
        age: 1,
        photo: 'imgs/char/ZanPartizanne.webp',
        pic: 'imgs/char/icons/KSA_The_Three_Mage-Sisters_icon.png',
        photoALT: 'imgs/char/more/zan.png',
        fact: 'Zan Partizanne is a thundery boss character introduced in Kirby Star Allies, known as the Electric General of The Three Mage-Sister',
    }, {
        firstName: 'Daroach',
        alt: 'Daroach',
        lastName: 'Planet Popstar',
        position: 'Claws',
        age: 2,
        photo: 'imgs/char/darach.png',
        pic: 'imgs/char/icons/KSA_Daroach_icon.png',
        photoALT: 'imgs/char/more/dar.png',
        fact: 'Daroach is a character from the Kirby: Squeak Squad game, where he is the leader of the Squeaks.',
    }, {
        firstName: 'Elfilin',
        alt: 'Elfilin',
        lastName: 'Planet Popstar',
        position: '???',
        age: 1,
        photo: 'imgs/char/KatFL_Elfilin_artwork.webp',
        pic: 'imgs/char/icons/KSA_Normal_icon.png',
        photoALT: 'imgs/char/more/eff.png',
        fact: 'Kirby`s primary companion. He is a flying chinchilla-like creature who is the compassionate half of Fecto Forgo, one of Forgotten Land`s antagonists',
    }, {
        firstName: 'Elline',
        alt: 'Elline',
        lastName: 'Planet Popstar',
        position: 'Art',
        age: 2,
        photo: 'imgs/char/KatRC_Elline_artwork2.webp',
        pic: 'imgs/char/icons/KSA_Normal_icon.png',
        photoALT: 'imgs/char/more/ell.png',
        fact: 'Elline is responsible for painting the Rainbow Rope which Kirby uses to get about in Seventopia',
    }, {
        firstName: 'Prince Fluff',
        alt: 'Prince',
        lastName: 'Planet Popstar',
        position: '???',
        age: 1,
        photo: 'imgs/char/Prince_Fluffbig.webp',
        pic: 'imgs/char/icons/KSA_Normal_icon.png',
        photoALT: 'imgs/char/more/pir.png',
        fact: 'Prince Fluff is a character in the Kirby series, appearing only in Kirby`s Epic Yarn and its remake, Kirby`s Extra Epic Yarn. He is the ruler of Patch Land.',
    },
]